### PR TITLE
add the .expose_loadbalancer.sh script

### PR DESCRIPTION
**Pull request by jmazzitelli**
add a script that will expose the loadbalancer via firewall port forward rules

### CODE REVIEW

**Comment by jmazzitelli** [comment]
@kxr This runs successfully, but I've not been able to access my cluster (on a headless server) via my laptop still. But it most likely is a problem on my end. Take a look and see if this is what you expect to work.

**Comment by jmazzitelli** [comment]
I can't seem to get this to work. This might not be the correct way to do this. I wonder if we need to use iptables instead? I am using NetworkManager, and I wonder if firewalld is playing nice with NM?

**Comment by jmazzitelli** [comment]
the script now adds the passthru rules for the $VIR_NET interface.

**Comment by jmazzitelli** [comment]
@kxr that last commit isn't right - the VIR_NET value is "default" for me - not "virb0". I will assume you know how to figure out how to get "virb0" - i do not see it anywhere in the env file.

**Comment by kxr** [comment]
@jmazzitelli Don't worry, I will take care of that. Just FYI, its quite easy. We just have to VIR_INT=$(virsh net-info ${VIR_NET} | grep Bridge | awk '{print $2}') to get the bridge interface of the libvirt network.

**Pull request merged**
